name: Firebase Hosting Deployment

on:
  push:
    branches: [ main, actions-workflow ]
  workflow_dispatch:

env:
  CI: ""

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: yarn
      - run: npm run build
      # - uses: w9jds/firebase-action@master
      #   with:
      #     args: deploy --only hosting
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}